### ISSUE TITLE
Repeat Traversals

### ISSUE THREAD

**Issue by SebastianAtWork** [ExRam/ExRam.Gremlinq#136]
**Describe the bug**
I am trying to upgrade my project from 7 to 8 and one particular change seems to me a bit strange. Repeat and RepeatUntil / UntilRepeat now expect the same Vertex type from start to finish:
![image](https://user-images.githubusercontent.com/19798013/106995553-710b3700-677f-11eb-9c35-6d46a24b3d0f.png)
That means i cannot traverse different Vertices anymore? Or is there a substitue for that? Breaks my code pretty hard.

**Expected behavior**
Repeat in gremlin doesnt care about what Vertices it traverses. Gremlinq < 8 also didnt care and gave the correct type anyway.

**Version information**
8.1.2

**Minimal working example**
No working example needed as its a question for the code of the library itself

**Comment by danielcweber** [comment]
It makes total sense. Say that you have a query of type Foo and you're repeating a subquery of type Bar, what type should the resulting query have? It may do the repetition > 0 times, then it's Foo. Otherwise it's Bar. You see, Gremlinq can't do no better than to force the same vertex type here. If you don't care, then do Cast<object>() before Repeat in also in the subquery.

**Comment by SebastianAtWork** [comment]
hmm okay, with that explanation it at least makes sense. Thank you
