### ISSUE TITLE
Export Subgraph

### ISSUE THREAD

**Issue by ancailliau** [ExRam/ExRam.Gremlinq#248]
I would like to export a subgraph, for visualization purposes, but I cannot figure out the best way to achieve the expected result. 

For example, the following describes the use of subgraph that seems to be unsupported: 
https://kelvinlawrence.net/book/Gremlin-Graph-Guide.html#subgraph

Do you have directions that could help? I'm ready to implement the support for the operator but I'm likely to require a bit of guidance. 

I could also simply iterate, but I don't know how I can get the identifier of From and To nodes for edges.

Thanks for your help,

**Comment by danielcweber** [comment]
Indeed the subgraph method is unsupported as of now, mainly because it's unsupported in CosmosDB which is what we mainly use (plus we didn't need it so far). The signature of subgraph looks a lot like the various As-methods in Gremlinq, given that they take a stepLabel. What I can't see right now is the shape of the results, i.e. what does a subgraph look like on the wire? How would the data structure for deserialization have to look like? Is it like in the Path-step, where we can't do better than 'object'? If you want to dive into this issue, feel free.

**Comment by ancailliau** [comment]
Cool, thanks. I'll have a look at it. How would you approach looking down on what's on the wire? What class(es) would you recommend me to look into/inspect first?

**Comment by danielcweber** [comment]
Once you have the subgraph method working to send a correct query to a server, get an [integration test (e.g. for Gremlin Server](https://github.com/ExRam/ExRam.Gremlinq/blob/main/test/ExRam.Gremlinq.Providers.GremlinServer.Tests/GremlinServerIntegrationTests.cs) going and set a breakpoint [here](https://github.com/ExRam/ExRam.Gremlinq/blob/bb5f2b8abd17d9ce8fbdf05e15053689f8f888b9/src/ExRam.Gremlinq.Providers.WebSocket/Extensions/GremlinQueryEnvironmentExtensions.cs#L79) to get the raw JToken that comes from the server. If you got an idea about what to deserialize the raw data to, and you figure that there's custom deserialization handling missing, override the appropriate handlers [here](https://github.com/ExRam/ExRam.Gremlinq/blob/main/src/ExRam.Gremlinq.Core/Deserialization/GremlinQueryFragmentDeserializer.cs).
