### ISSUE TITLE
Support declarative label name for schema bound graph element

### ISSUE THREAD

**Issue by veeg** [ExRam/ExRam.Gremlinq#3]
Add support for the `IVertex` model to provide the label name in the graph. Currently, the label name is derived from the type name.

See equivalent functionality in [Gremlin.Net.CosmosDb](https://github.com/evo-terren/Gremlin.Net.CosmosDb/blob/94e1fe861aa9d0429b937d41a4a4e0a287d30730/src/Gremlin.Net.CosmosDb/Structure/LabelAttribute.cs#L10-L26)

Example:
```dotnet
[Label("user")]
public class User : Vertex
{
}

// The vertices in the graph has the label "user", not "User".
let result = await g.v<User>.ToArray();
```

**Comment by danielcweber** [comment]
Have a look at the changes in [this commit](https://github.com/ExRam/ExRam.Gremlinq/commit/304f5aad57f14057d44c21922bc85accdb49d85e). It allows you to modify your model to make all labels lowercase. What do you think of it?

I'm currently not sure whether to go for the attribute solution, at least not out-of-the-box, since there is always a possibility that developers not have access to the source of the used POCOs.

However, that doesn't mean that there cannot be a separate library, either 3rd party or within the Gremlinq solution, that would provide support for annotiations through attributes. Gremlinqs IGraphModel-approach definitely allows this.

**Comment by veeg** [comment]
It is certainly an improvement that would fulfill my current use-case.

I have no strong opinions on either solutions, as long as there is _some_ solution to modify the derivative of types into graph labels.

**Comment by danielcweber** [comment]
There'll be a new minor release next week.

**Comment by danielcweber** [comment]
Just released version a new version of Gremlinq: https://www.nuget.org/packages/ExRam.Gremlinq.Core/6.4.1.

You can now use `WithLowercaseLabels` on your `IGraphModel`. Unfortunately, there are no extension points yet to have properties in lower case. I might consider this in a future major release. Ideas and PRs are always welcome!
