### ISSUE TITLE
NotImplementedException when using StepLabels as decribed in Docs

### ISSUE THREAD

**Issue by Dmo16** [ExRam/ExRam.Gremlinq#376]
**Describe the bug**
When attempting to use step labels, like so: 

```
       public async Task<Person> ReturnTuples()
        {
            try
            {
                var result = await _g
                    .V<Person>()
                    .As((__, person) => __
                        .Out<Knows>()
                        .OfType<Person>()
                        .As((__, friend) => __
                            .Select(person, friend)));

                return result[0].Item1;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
        }
```

Docs example: 

![image](https://user-images.githubusercontent.com/45639728/116907132-29c20480-ac0f-11eb-8061-5785a07c652b.png)

The query fails. While debugging, I found that the following exception is thrown, on the `.As(( __ , person)` step:

Exception: 

```
System.NotImplementedException: The conversion operator on StepLabel is not intended to be called. It's use is to appear in expressions only.

   at ExRam.Gremlinq.Core.StepLabel`1.ThrowConversion() in /_/src/ExRam.Gremlinq.Core/Queries/StepLabel.cs:line 72
   at ExRam.Gremlinq.Core.StepLabel`1.get_Value() in /_/src/ExRam.Gremlinq.Core/Queries/StepLabel.cs:line 67
```

**Expected behavior**
I expect the code to return a tuple, as described in the documentation provided on the repo

**Version information**
ExRam.Gremlin.Core.AspNet version 8.5.0

Here is a small repo that contains a simple XUnit test and a simple method that implements the steps:

https://github.com/Dmo16/GremLinQMinRepo

**Additional context**

I _think_ what may be happening is that the thrown exception from the GremlinQ query is affecting how the Gremlin query is formed, and thus we get this error, from a malformed query.

Here's the error that comes back from the Cosmos DB when attempting the query above: 

NOTE: `Syntax error, incorrect syntax near 'group'."}]}` Group is what I've chosen as the partition key for this little test DB.

```
Gremlin.Net.Driver.Exceptions.ResponseException
ScriptEvaluationError: 

ActivityId : 444a9316-1d96-4d0c-bc0e-7ca0dc3c9008
ExceptionType : BadRequestException
ExceptionMessage :
	Message: {"errors":[{"severity":"Error","location":{"start":673,"end":678},"code":"SC1001","message":"Syntax error, incorrect syntax near 'group'."}]}
	ActivityId: 444a9316-1d96-4d0c-bc0e-7ca0dc3c9008, documentdb-dotnet-sdk/2.11.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
Source : Microsoft.Azure.Documents.ClientMessage: {"errors":[{"severity":"Error","location":{"start":673,"end":678},"code":"SC1001","message":"Syntax error, incorrect syntax near 'group'."}]}
ActivityId: 444a9316-1d96-4d0c-bc0e-7ca0dc3c9008, documentdb-dotnet-sdk/2.11.0 Host/64-bit MicrosoftWindowsNT/6.2.9200.0
	BackendStatusCode : BadRequest
	BackendActivityId : 444a9316-1d96-4d0c-bc0e-7ca0dc3c9008
	HResult : 0x80131500
```

Additional screenshot of the debug breakpoints:

![Screenshot 2021-05-03 130158](https://user-images.githubusercontent.com/45639728/116907600-cab0bf80-ac0f-11eb-97e4-e4cb2ad25e39.png)

**Comment by danielcweber** [comment]
Sorry to say it works perfectly well for me (notice I had to change the 'group' property to 'PartitionKey' because that is what my partition key is called). I'm puzzled though: Maybe 'group' is a reserved word in CosmosDB?

![image](https://user-images.githubusercontent.com/1899410/116911599-598cfe80-ac47-11eb-9b2d-b59a71b43f76.png)


You are actually describing two separate errors here: One that's thrown locally on constructing the query, and another on the server. What probably looks like an error for you locally is any use of `StepLabel.Value` which, as the exception says, is not intended to be executed anywhere, but may only appear in expressions. In the debug view, of course, you'll encounter the exception, but that's no problem. It doesn't throw in your code, but only in the debugger view.

![image](https://user-images.githubusercontent.com/1899410/116911817-a375e480-ac47-11eb-80c1-bdbe4a9a78a6.png)

I can't make sense of the remote error though. Call `Debug` on your query, like

![image](https://user-images.githubusercontent.com/1899410/116912297-50e8f800-ac48-11eb-9eb4-9859b6f2f652.png)

and post it here but also throw it into the CosmosDB Data Explorer directly and see what is does.

**Comment by danielcweber** [comment]
Add: It even works for me with the group-Property intact (+ additional PartitionKey property)

![image](https://user-images.githubusercontent.com/1899410/116913429-bf7a8580-ac49-11eb-8390-500c81802662.png)

**Comment by Dmo16** [comment]
Hi @danielcweber , thanks for getting back to me so quickly.

I think you can consider this closed:

I'm at a loss at this point. My original project that produced this error is now functioning correctly as well, just as your second screen shot shows. 

Maybe I made a query mistake and fixed it while refactoring some other code :)

Sorry for the inconvenience!
