### ISSUE TITLE
Singleton QuerySource

### ISSUE THREAD

**Issue by jseekamp** [ExRam/ExRam.Gremlinq#4]
For long running applications do you suggest using a singleton IConfigurableGremlinQuerySource or should a new one be created for each query? Should this issue be taken into account?

https://issues.apache.org/jira/browse/TINKERPOP-2090

I also found this comment that suggests checking the server connection count, but this is not exposed on the IConfigurableGremlinQuerySource

https://github.com/MicrosoftDocs/azure-docs/issues/14520#issuecomment-463940136

Help would be greatly appreciated! Thanks for the great library.

**Comment by danielcweber** [comment]
The IGremlinQuerySource does not ever establish or keep up a connection. Connections will only come into play when a query is executed. The underlying Gremlin.net driver will deal with that. And since all IGremlinQuery and IGremlinQuerySource instances are immutable, it's safe and probably a good idea to singleton cache them (or even use a DI container).

**Comment by jseekamp** [comment]
This was helpful; however, when connecting to a CosmosDB server this doesn't work. After a period of time the singleton IGremlinQuerySource gets into a completely unusable state. This is 100% a Gremlin.net driver issue though. The issue is being tracked at https://issues.apache.org/jira/browse/TINKERPOP-2090. I think it makes sense to close this issue.

**Comment by danielcweber** [comment]
An upcoming version updates Gremlinqs dependency on Gremlin.net. It might be resolved then.
