### ISSUE TITLE
How can you configure ASP.NET driver through code?

### ISSUE THREAD

**Issue by gfaraj** [ExRam/ExRam.Gremlinq#802]
I'm looking for a way to configure the Gremlin host/key/etc. from code rather than from a configuration file. I have not found documentation or a sample for that. I'm using the Cosmos ASP.NET driver, and I'm using it from an Azure Function. Can you help?

**Comment by danielcweber** [comment]
The 'Console'-part of the [Gremlinq samples project](https://github.com/ExRam/ExRam.Gremlinq.Samples) might help.

**Comment by gfaraj** [comment]
Hey @danielcweber that kinda helps, thanks. I still want to register the query source as a service in DI though, and I'm failing to find a way to configure it within that statement. If you don't have an example of that handy, I'll keep tinkering with it.

**Comment by gfaraj** [comment]
I was able to figure it out, thanks. For others that may want the same, here it is:

    services.AddGremlinq(setup => setup
        .UseCosmosDb<Vertex, Edge>(x => x.PartitionKey,
          providerSetup => providerSetup.Configure((configurator, providerSection) =>
          {
            configurator = configurator.At(new Uri(Environment.GetEnvironmentVariable("GremlinHost")));
            configurator = configurator.OnDatabase("MyGraphDatabase");
            configurator = configurator.OnGraph("Friends");
            configurator = configurator.AuthenticateBy(Environment.GetEnvironmentVariable("GremlinPrimaryKey"));

            return configurator;
          })));

@danielcweber -- is there any way to configure the graph name on a per-instance basis? For example, if I want to use 2 different graphs in my project, how would I go about doing that?

**Comment by danielcweber** [comment]
You can create any number of `IGremlinQuerySource` instances ([as shown in the samples](https://github.com/ExRam/ExRam.Gremlinq.Samples/blob/e1f7393f534cc1efd6453040aba352d4cd0ae1bb/ExRam.Gremlinq.Samples.Console/Program.cs#L23)) and register them manually in any `IServiceCollection` or store them otherwise. Injecting different instances of a service into different other service is an issue of its own, not necessarily of Gremlinq. I know that e.g. AutoFac has some registration modulator (named something like `WhenInjectedInto`), but that might not help you with Microsoft DI.
